### ISSUE TITLE
Update Statement request - Exclude fields Or automatique mapping of fields received

### ISSUE THREAD

**Issue by aleblanc70** [kataras/pg#2]
Hi,

Continue playing with pg and Iris. 
I use CockroachDB. Currently when we used a CreatedAt or UpdateAt has Timestamp it will create a trigger to assign those field and it's a great feature!

CockroachDB, do not support trigger so I renamed my audit field to CrtdAt and UpdtAt.

So now in my Create method, I will assign both CrtdAt and UpdtAt with time.Now()
And now in my Update method, I will assign only UpdtAt with time.Now()

Because, my json do not send back my CrtdAt field, the CrtdAt is reset to default value

"id": "7b303113-18f7-443b-a2a0-9609fab7beb9",
**"crtdAt": "0001-01-01T00:00:00Z",**
"updAt": "2023-07-07T01:22:26.17382Z",
"email": "IronMan5@gmail.com",
"password": "$2a$06$NTf24l4/IAhapOktfoDewu749lpxm2EV6ZKuiqFxL7SYqb2r1CGpm",
"firstName": "André",
"middleName": "sssssssss",
"lastName": "Leblanc",
"sex": "M"

If we have a way to exclude field instead of UpdateOnly:
`return repo.UpdateOnlyColumns(ctx, nil, values...)`
I could just exclude my CrtdAt on Update.

OR

Event better, if the Update SQL statement was base only on the received fields from the body.
We need to make sure when we create the record all our non null fields are valid. Then we should be good.

What do you think does it make senses ? 

```
type User struct {
	Id         string    `json:"id" pg:"type=uuid,primary"`
	CrtdAt     time.Time `json:"crtdAt" pg:"type=TIMESTAMPTZ"`
	UpdAt      time.Time `json:"updAt" pg:"type=TIMESTAMPTZ"`
	Email      string    `json:"email" pg:"type=varchar(255),username,unique"`
	Password   string    `json:"password" pg:"type=varchar(128),password"`
	FirstName  string    `json:"firstName" pg:"type=varchar(255)"`
	MiddleName *string   `json:"middleName" pg:"type=varchar(255),null"`
	LastName   string    `json:"lastName" pg:"type=varchar(255)"`
	Sex        *string   `json:"sex" pg:"type=char(1),null"`
}
```

Thanks!

**Comment by kataras** [comment]
Hello @aleblanc70, the update with exclude is a good idea, I am going to add it, but I think you don't need it. Did you try to add the `,default=clock_timestamp()"` to your CrtdAt and UpdAt fields?

Also, the update method has already checks for nulls, but because someone may want to set the timestamp fields to empty we allow this on update, except when the pg go field has a default value of `clock_timestamp()` or `now()` then we let database to set it when this value is zero.

**Comment by kataras** [comment]
OK @aleblanc70, I have added the new `UpdateExceptColumns` method, can you try it and reply back if that works for you?

**Comment by kataras** [comment]
OK @aleblanc70, I have added the new `UpdateExceptColumns` method, can you try it and reply back if that works for you?

```sh
go get github.com/kataras/pg@main
```

**Comment by aleblanc70** [comment]
With UpdateExceptColumns

I got the error 
exec: ERROR: multiple assignments to the same column "id" (SQLSTATE 42601)

My Code
https://github.com/aleblanc70/events-pg/blob/main/api/main.go

Also, if I change for: UpdateOnlyColumns

no arguments found for update, maybe missing struct field tag of "pg"

**Comment by kataras** [comment]
@aleblanc70 you column fields does not match the `except` ones that's why you getting the error probably.

When you don't define a column name (`pg:"name=columnName..."`) in your struct field tag, the default column name is the lowercase version of the struct field name and if it contains an uppercase letter then it adds a `_` except `ID, URL`. For example
```go
Title string `pg:"type=varchar(255),unique
```
^ The column name is not `Title` but `title`.

I assume you are using lowercase for your column naming in your database, right? If no, please specifiy the name tag option (`Title string `pg:"name=Title,type=varchar(255),unique"`) or I can add a global variable which you can use to declare to keep the column names same as the struct field names if the name tag option is missing.

If the column name in your database are in lowercase, then you need to pass those column names instead of this: 
```go
except := []string{"Title", "EndAt", "UpdAt", "CrtdAt", "ID"}
```
to:
```go
except := []string{"title", "end_at", "upd_at", "crtd_at", "id"}
```

**Comment by kataras** [comment]
@aleblanc70 you column fields does not match the `except` ones that's why you getting the error probably.

When you don't define a column name (`pg:"name=columnName..."`) in your struct field tag, the default column name is snake_case version of the struct field name. For example:
```go
Title string `pg:"type=varchar(255),unique"`
```
^ The column name is not `Title` but `title`.

I assume you are using lowercase for your column naming in your database, right? If no, please specifiy the name tag option:
```go
Title string `pg:"name=Title,type=varchar(255),unique"`
```

Or I can add a global variable which you can use to declare to keep the column names same as the struct field names if the name tag option is missing.

If the column name in your database are in lowercase, then you need to pass those column names instead of this: 
```go
except := []string{"Title", "EndAt", "UpdAt", "CrtdAt", "ID"}
```
to:
```go
except := []string{"title", "end_at", "upd_at", "crtd_at", "id"}
```

**Comment by kataras** [comment]
@aleblanc70 you column fields does not match the `except` ones that's why you getting the error probably.

When you don't define a column name (`pg:"name=columnName..."`) in your struct field tag, the default column name is snake_case version of the struct field name. For example:
```go
Title string `pg:"type=varchar(255),unique"`
```
^ The column name is not `Title` but `title`.

I assume you are using lowercase for your column naming in your database, right? If no, please specifiy the name tag option:
```go
Title string `pg:"name=Title,type=varchar(255),unique"`
```

Or call the **new** `pg.SetKeepColumnName(true)` before everything else to keep the column names same as the struct field names when the tag option `name` is missing.

If the column name in your database are in lowercase, then you need to pass those column names instead of this: 
```go
except := []string{"Title", "EndAt", "UpdAt", "CrtdAt", "ID"}
```
to:
```go
except := []string{"title", "end_at", "upd_at", "crtd_at", "id"}
```

**Comment by kataras** [comment]
@aleblanc70 The column names to except do not match the schema's ones, that's why you getting that error. Why they don't match? Answer follows up:

When you don't define a column name (`pg:"name=columnName..."`) in your struct field tag, the default column name is snake_case version of the struct field name. For example:
```go
Title string `pg:"type=varchar(255),unique"`
```
^ The column name is not `Title` but `title`.

I assume you are using lowercase for your column naming in your database, right? If no, please specifiy the name tag option:
```go
Title string `pg:"name=Title,type=varchar(255),unique"`
```

Or call the **new** `pg.SetDefaultColumnNameMapper(pg.NoColumnNameMapper)` before everything else to keep the column names same as the struct field names when the tag option `name` is missing OR if you want to use the JSON naming: `pg.SetDefaultColumnNameMapper(pg.JSONColumnNameMapper)`

```sh
$ go get github.com/kataras/pg@main
```

```go
func init() {
    pg.SetDefaultColumnNameMapper(pg.NoColumnNameMapper)
}
```

If the column name in your database are in lowercase, then you need to pass those column names instead of this: 
```go
except := []string{"Title", "EndAt", "UpdAt", "CrtdAt", "ID"}
```
to:
```go
except := []string{"title", "end_at", "upd_at", "crtd_at", "id"}
```

**Comment by kataras** [comment]
@aleblanc70 The column names to except do not match the schema's ones, that's why you getting that error. Why they don't match? Answer follows up:

When you don't define a column name (`pg:"name=columnName..."`) in your struct field tag, the default column name is snake_case version of the struct field name. For example:

```go
Title string `pg:"type=varchar(255),unique"`
```

^ The column name is converted to `title`.

You can set a custom column name for each field by passing the `name` pg struct field tag option:

```go
Title string `pg:"name=Title,type=varchar(255),unique"`
```

You can also set a global column name mapper for all column names if the `name` pg struct field tag option is missing, as shown below:

```sh
$ go get github.com/kataras/pg@main
```

To keep the column names same as the struct field names (Title -> Title, CrtdAt -> CrtdAt):
```go
func init() {
    pg.SetDefaultColumnNameMapper(pg.NoColumnNameMapper)
}
```

```go
except := []string{"Title", "EndAt", "UpdAt", "CrtdAt", "ID"}
```

To convert the column names to their `json` struct field (if exists, otherwise field name):

```go
func init() {
    pg.SetDefaultColumnNameMapper(pg.JSONColumnNameMapper)
}
```

```go
except := []string{"title", "endAt", "updAt", "crtdAt", "id"}
```

To keep the default behavior (snake_case column names), just change your `except` list to (Title -> title, CrtdAt -> crtd_at):

```go
except := []string{"title", "end_at", "upd_at", "crtd_at", "id"}
```

**Comment by kataras** [comment]
@aleblanc70 The column names to except do not match the schema's ones, that's why you getting that error. Why they don't match? Answer follows up:

When you don't define a column name (`pg:"name=columnName..."`) in your struct field tag, the default column name is snake_case version of the struct field name. For example:

```go
Title string `pg:"type=varchar(255),unique"`
```

^ The column name is converted to `title`.

You can set a custom column name for each field by passing the `name` pg struct field tag option:

```go
Title string `pg:"name=Title,type=varchar(255),unique"`
```

You can also set a global column name mapper for all column names if the `name` pg struct field tag option is missing, as shown below:

```sh
$ go get github.com/kataras/pg@main
```

To keep the column names same as the struct field names (Title -> Title, CrtdAt -> CrtdAt):
```go
func init() {
    pg.SetDefaultColumnNameMapper(pg.NoColumnNameMapper)
}
```

```go
except := []string{"Title", "EndAt", "UpdAt", "CrtdAt", "ID"}
```

To convert the column names to their `json` struct field (if exists, otherwise field name):

```go
func init() {
    pg.SetDefaultColumnNameMapper(pg.JSONColumnNameMapper)
}
```

```go
except := []string{"title", "endAt", "updAt", "crtdAt", "id"}
```

To keep the default behavior (snake_case column names), just change your `except` list to (Title -> title, CrtdAt -> crtd_at):

```go
except := []string{"title", "end_at", "upd_at", "crtd_at", "id"}
```

-----

Bonus tips:

To log all the performed queries you can register a logger:

```go
import (
  // ...
  "github.com/kataras/golog"
  "pgxgolog "github.com/kataras/pgx-golog"
)

// ...
db, err := pg.Open(
  context.Background(),
  schema,
  dsn,
  pg.WithLogger(pgxgolog.NewLogger(golog.Default))) // <- HERE
```

You don't have to set `type=TIMESTAMPTZ`, you can use its lowercase version as well `type=timestamptz`.

Please don't hesitate to reply back if the problem was not solved!

**Comment by kataras** [comment]
@aleblanc70 The column names to except (`except` string slice) do not match the schema's ones. But why they don't match? Answer follows up:

When you don't define a column name (`pg:"name=columnName..."`) in your struct field tag, the default column name is snake_case version of the struct field name. For example:

```go
Title string `pg:"type=varchar(255),unique"`
```

^ The column name is converted to `title`.

You can set a custom column name for each field by passing the `name` pg struct field tag option:

```go
Title string `pg:"name=Title,type=varchar(255),unique"`
```

You can also set a global column name mapper for all column names if the `name` pg struct field tag option is missing, as shown below:

```sh
$ go get github.com/kataras/pg@main
```

To keep the column names same as the struct field names (Title -> Title, CrtdAt -> CrtdAt):
```go
func init() {
    pg.SetDefaultColumnNameMapper(pg.NoColumnNameMapper)
}
```

```go
except := []string{"Title", "EndAt", "UpdAt", "CrtdAt", "ID"}
```

To convert the column names to their `json` struct field (if exists, otherwise field name):

```go
func init() {
    pg.SetDefaultColumnNameMapper(pg.JSONColumnNameMapper)
}
```

```go
except := []string{"title", "endAt", "updAt", "crtdAt", "id"}
```

To keep the default behavior (snake_case column names), just change your `except` list to (Title -> title, CrtdAt -> crtd_at):

```go
except := []string{"title", "end_at", "upd_at", "crtd_at", "id"}
```

-----

Bonus tips:

To log all the performed queries you can register a logger:

```go
import (
  // ...
  "github.com/kataras/golog"
  pgxgolog "github.com/kataras/pgx-golog"
)

// ...
db, err := pg.Open(
  context.Background(),
  schema,
  dsn,
  pg.WithLogger(pgxgolog.NewLogger(golog.Default))) // <- HERE
```

You don't have to set `type=TIMESTAMPTZ`, you can use its lowercase version as well `type=timestamptz`.

Please don't hesitate to reply back if the problem was not solved!

**Comment by aleblanc70** [comment]
It work great now thanks for your help! :)

**Comment by kataras** [comment]
You're welcome @aleblanc70! Glad to help
